#!/bin/bash
set -e

echo "DB_USER: $DB_USER"
echo "DB_USER_PASSWORD is set: ${DB_USER_PASSWORD:+yes}"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" \
  <<-EOSQL
    CREATE USER "$DB_USER" WITH PASSWORD '$DB_USER_PASSWORD';
    GRANT CONNECT ON DATABASE "$POSTGRES_DB" TO "$DB_USER";
    GRANT USAGE ON SCHEMA public TO "$DB_USER";
    GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO "$DB_USER";
    GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO "$DB_USER";
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "$DB_USER";
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO "$DB_USER";
EOSQL

echo "App user created successfully"